repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.72.1
  hooks:
    -   id: terraform_fmt
        name: fmt
        entry: "make"
        pass_filenames: true
        args:
          - format
        always_run: true
        files: (\.tf|\.tfvars)$
        language: system
    -   id: terraform_validate
        name: validate
        entry: "make"
        pass_filenames: true
        stages: [commit]
        args:
          - validate
        files: (\.tf|\.tfvars)$
        language: system
    -   id: terraform_docs
        name: docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
        always_run: true