trigger: none
pr: 
  - main

parameters:
  - name: OPGROUP
    displayName: 'Terraform variable file used for specified Op Group'
    type: string
    default: contino
    values:
      - caf
      - caf-canary
      - contino
      - corp
      - grpm
      - grpmua
      - gry      
      - wpp
      - wppit
      - oglvy
      - hgrth
      - hk
      - wt
      - vmlyr
      - vmlyrua

resources:
  repositories:
    - repository: templates
      type: github
      name: WPP-Internal/wpp-it-azure-terraform-pipeline-template
      ref: refs/tags/v2.1.3
      endpoint: "Azure Landing Zone GitHub OAuth Service Connection (USE THIS ONLY ONLY)" # Set in Terraform

extends:
  template: pipeline_cd.yml@templates
  parameters:   
    CHECKOV: true
    OPGROUP: ${{ parameters.OPGROUP }}
    SUBSCRIPTION_NAME: '' # If you are running the pipeline against OpGroup level leave this as ''
