project_name            = "Cloud Hub Azure Landing Zone"
github_repo             = "WPP-Internal/wpp-it-azure-subscription-vending"
service_connection_name = "Azure Landing Zone GitHub OAuth Service Connection (USE THIS ONLY ONLY)"
service_connection_id   = "a0edc04f-e4e0-4095-b6a6-1ed569ff56ab"
pipeline_yml_name       = "pipeline"